#!/bin/bash
# IP Command Helper with Persistence
# Save as: ip-helper.sh

# ==================== CONFIGURATION & GLOBALS ====================
CONFIG_FILE="/etc/network/interfaces.d/ip-helper-persistent"
BACKUP_DIR="/etc/network/interfaces.d/backups"
LOG_FILE="/tmp/ip-command-helper.log"
declare -A INTERFACE_CONFIGS
SELECTED_INTERFACE=""
COMMAND_PREVIEW=""

# ==================== INITIALIZATION ====================
initialize() {
    # Create necessary directories
    mkdir -p "$(dirname "$CONFIG_FILE")" "$BACKUP_DIR" 2>/dev/null || true
    touch "$LOG_FILE"
    
    # Load existing persistent configurations
    load_persistent_configs
    
    # Check for root privileges
    if [ "$EUID" -ne 0 ]; then
        echo "Warning: Some commands require sudo. Using 'sudo' where needed."
        SUDO_CMD="sudo"
    else
        SUDO_CMD=""
    fi
}

# ==================== PERSISTENCE FUNCTIONS ====================
load_persistent_configs() {
    if [ -f "$CONFIG_FILE" ]; then
        echo "Loading persistent configurations from $CONFIG_FILE"
        source "$CONFIG_FILE" 2>/dev/null || true
    fi
}

save_to_persistent() {
    local interface="$1"
    local config_type="$2"
    local value="$3"
    
    # Create backup
    local timestamp=$(date +%Y%m%d_%H%M%S)
    cp "$CONFIG_FILE" "${BACKUP_DIR}/interfaces_${timestamp}.bak" 2>/dev/null || true
    
    # Save to config file
    {
        echo "# Auto-generated by ip-helper script"
        echo "# Last updated: $(date)"
        echo ""
        for iface in "${!INTERFACE_CONFIGS[@]}"; do
            echo "INTERFACE_CONFIGS[$iface]='${INTERFACE_CONFIGS[$iface]}'"
        done
    } > "$CONFIG_FILE"
    
    log_action "SAVED: $config_type for $interface: $value"
    echo "✓ Configuration saved persistently"
}

apply_persistent_configs() {
    if [ -f "$CONFIG_FILE" ]; then
        echo "Applying persistent configurations..."
        source "$CONFIG_FILE" 2>/dev/null || true
        
        for iface in "${!INTERFACE_CONFIGS[@]}"; do
            echo "  Applying config for $iface..."
            # Here you would parse and apply the saved configurations
            # This is a simplified version
        done
        echo "✓ Persistent configurations applied"
    fi
}

# ==================== UTILITY FUNCTIONS ====================
log_action() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >> "$LOG_FILE"
}

validate_interface() {
    # Extract just the child interface name (before the @)
    local interface_name="${1%%@*}"
    
    if ! ip link show "$1" &>/dev/null; then
        echo "ERROR: Interface '$1' does not exist."
        return 1
    fi
    return 0
}

show_current_state() {
    local interface_name="${SELECTED_INTERFACE%%@*}"
    
    echo ""
    echo "========================================="
    echo "CURRENT STATE for $SELECTED_INTERFACE"
    echo "========================================="
    ip -brief addr show dev "$SELECTED_INTERFACE" 2>/dev/null || echo "Interface not found"
    ip -brief link show dev "$SELECTED_INTERFACE" 2>/dev/null || echo "Interface not found"
    echo "========================================="
    echo ""
}

execute_with_preview() {
    echo ""
    echo "Command to execute:"
    echo "  $COMMAND_PREVIEW"
    echo ""
    
    read -p "Execute this command? (y/N): " confirm
    case $confirm in
        [yY]|[yY][eE][sS])
            echo "Executing: $COMMAND_PREVIEW"
            eval "$SUDO_CMD $COMMAND_PREVIEW"
            if [ $? -eq 0 ]; then
                echo "✓ Command executed successfully."
                log_action "EXECUTED: $COMMAND_PREVIEW"
                
                # Ask about persistence
                read -p "Save this change persistently? (y/N): " save_confirm
                if [[ "$save_confirm" =~ ^[Yy]$ ]]; then
                    # Extract configuration type and value from command
                    local config_type=""
                    local config_value=""
                    
                    if [[ "$COMMAND_PREVIEW" == *"addr add"* ]]; then
                        config_type="IP"
                        config_value=$(echo "$COMMAND_PREVIEW" | grep -oP 'addr add \K[^ ]+')
                    elif [[ "$COMMAND_PREVIEW" == *"link add"* && "$COMMAND_PREVIEW" == *"vlan"* ]]; then
                        config_type="VLAN"
                        config_value=$(echo "$COMMAND_PREVIEW" | grep -oP 'name \K[^ ]+')
                    elif [[ "$COMMAND_PREVIEW" == *"link set"* && "$COMMAND_PREVIEW" == *"mtu"* ]]; then
                        config_type="MTU"
                        config_value=$(echo "$COMMAND_PREVIEW" | grep -oP 'mtu \K[^ ]+')
                    fi
                    
                    if [ -n "$config_type" ] && [ -n "$config_value" ]; then
                        save_to_persistent "$SELECTED_INTERFACE" "$config_type" "$config_value"
                    fi
                fi
            else
                echo "✗ Command failed with error."
            fi
            ;;
        *)
            echo "Command cancelled."
            ;;
    esac
    read -p "Press Enter to continue..."
}

# ==================== INTERFACE SELECTION ====================
select_interface() {
    clear
    echo "========================================"
    echo "    IP COMMAND HELPER - Select Interface"
    echo "========================================"
    echo ""
    
    # Get list of interfaces
    declare -a interfaces_display  # For display (e.g., virbr1.1@virbr1)
    declare -a interfaces_clean    # For commands (e.g., virbr1.1)
    local count=1
    
    echo "Available network interfaces:"
    while read -r line; do
        # Get the full interface name from ip command
        full_iface=$(echo "$line" | awk '{print $1}')
        state=$(echo "$line" | awk '{print $3}')
        
        # Store both display and clean names
        interfaces_display[$count]="$full_iface"
        
        # Extract clean name (remove @parent part)
        clean_iface="${full_iface%%@*}"
        interfaces_clean[$count]="$clean_iface"
        
        echo "  $count. $clean_iface ($state)"
        ((count++))
    done < <(ip -brief link show)
    
    echo ""
    echo "  $count. Apply persistent configurations"
    echo "  $((count+1)). Exit program"
    echo ""
    
    local total_options=$((count+1))
    read -p "Select option (1-$total_options): " choice
    
    if [ "$choice" -eq "$count" ]; then
        apply_persistent_configs
        read -p "Press Enter to continue..."
        return 2
    elif [ "$choice" -eq "$total_options" ]; then
        echo "Exiting. Goodbye!"
        exit 0
    elif [ "$choice" -ge 1 ] && [ "$choice" -lt "$count" ]; then
        # Store the CLEAN interface name for commands
        SELECTED_INTERFACE="${interfaces_clean[$choice]}"
        echo "Selected interface: ${interfaces_display[$choice]}"
        return 0
    else
        echo "Invalid selection!"
        read -p "Press Enter to continue..."
        return 1
    fi
}

# ==================== MODULE MENUS ====================
module_link() {
    while true; do
        clear
        echo "=== LINK MODULE (Layer 2) ==="
        echo "Interface: $SELECTED_INTERFACE"
        show_current_state
        echo ""
        echo "1. Bring interface UP"
        echo "2. Bring interface DOWN"
        echo "3. Set MTU"
        echo "4. Change MAC address"
        echo "5. Set promiscuous mode"
        echo "6. Create VLAN subinterface"
        echo "7. Create bridge"
        echo "8. Add interface to bridge"
        echo "9. Create bond interface"
        echo "10. Show detailed link info"
        echo "0. Back to interface selection"
        echo ""
        
        read -p "Select operation: " choice
        
        case $choice in
            1)
                COMMAND_PREVIEW="ip link set dev $SELECTED_INTERFACE up"
                execute_with_preview
                ;;
            2)
                COMMAND_PREVIEW="ip link set dev $SELECTED_INTERFACE down"
                execute_with_preview
                ;;
            3)
                read -p "Enter MTU value (68-9000): " mtu_value
                if [[ "$mtu_value" =~ ^[0-9]+$ ]] && [ "$mtu_value" -ge 68 ] && [ "$mtu_value" -le 9000 ]; then
                    COMMAND_PREVIEW="ip link set dev $SELECTED_INTERFACE mtu $mtu_value"
                    execute_with_preview
                else
                    echo "Invalid MTU value."
                    read -p "Press Enter to continue..."
                fi
                ;;
            4)
                read -p "Enter new MAC address (format: aa:bb:cc:dd:ee:ff): " mac_addr
                if [[ "$mac_addr" =~ ^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$ ]]; then
                    COMMAND_PREVIEW="ip link set dev $SELECTED_INTERFACE address $mac_addr"
                    execute_with_preview
                else
                    echo "Invalid MAC address format."
                    read -p "Press Enter to continue..."
                fi
                ;;
            5)
                echo "1. Enable promiscuous mode"
                echo "2. Disable promiscuous mode"
                read -p "Select: " promisc_choice
                if [ "$promisc_choice" = "1" ]; then
                    COMMAND_PREVIEW="ip link set dev $SELECTED_INTERFACE promisc on"
                    execute_with_preview
                elif [ "$promisc_choice" = "2" ]; then
                    COMMAND_PREVIEW="ip link set dev $SELECTED_INTERFACE promisc off"
                    execute_with_preview
                fi
                ;;
            6)
                read -p "Enter VLAN ID (1-4094): " vlan_id
                read -p "Enter VLAN interface name (e.g., ${SELECTED_INTERFACE}.100): " vlan_name
                if [[ "$vlan_id" =~ ^[0-9]+$ ]] && [ "$vlan_id" -ge 1 ] && [ "$vlan_id" -le 4094 ]; then
                    COMMAND_PREVIEW="ip link add link $SELECTED_INTERFACE name $vlan_name type vlan id $vlan_id"
                    execute_with_preview
                    
                    # Ask to bring it up and add IP
                    if [ $? -eq 0 ]; then
                        read -p "Bring up the VLAN interface and add IP? (y/N): " vlan_setup
                        if [[ "$vlan_setup" =~ ^[Yy]$ ]]; then
                            $SUDO_CMD ip link set dev "$vlan_name" up
                            read -p "Enter IP address for VLAN (e.g., 192.168.100.1/24): " vlan_ip
                            if [[ "$vlan_ip" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/[0-9]+$ ]]; then
                                $SUDO_CMD ip addr add "$vlan_ip" dev "$vlan_name"
                                echo "VLAN interface configured."
                            fi
                        fi
                    fi
                else
                    echo "Invalid VLAN ID."
                    read -p "Press Enter to continue..."
                fi
                ;;
            7)
                read -p "Enter bridge name (e.g., br0): " bridge_name
                COMMAND_PREVIEW="ip link add name $bridge_name type bridge"
                execute_with_preview
                if [ $? -eq 0 ]; then
                    $SUDO_CMD ip link set dev "$bridge_name" up
                fi
                ;;
            8)
                read -p "Enter bridge name to add to: " bridge_name
                if ip link show type bridge | grep -q "$bridge_name"; then
                    COMMAND_PREVIEW="ip link set dev $SELECTED_INTERFACE master $bridge_name"
                    execute_with_preview
                else
                    echo "Bridge $bridge_name not found."
                    read -p "Press Enter to continue..."
                fi
                ;;
            9)
                read -p "Enter bond name (e.g., bond0): " bond_name
                read -p "Enter bond mode (balance-rr, active-backup, etc.): " bond_mode
                COMMAND_PREVIEW="ip link add name $bond_name type bond mode $bond_mode"
                execute_with_preview
                ;;
            10)
                echo ""
                ip -details link show dev "$SELECTED_INTERFACE"
                read -p "Press Enter to continue..."
                ;;
            0)
                return
                ;;
            *)
                echo "Invalid option."
                sleep 1
                ;;
        esac
    done
}

module_address() {
    while true; do
        clear
        echo "=== ADDRESS MODULE (Layer 3 - IP) ==="
        echo "Interface: $SELECTED_INTERFACE"
        show_current_state
        echo "1. Add IP address"
        echo "2. Delete IP address"
        echo "3. Flush all IP addresses"
        echo "4. Show all IP addresses"
        echo "0. Back to interface selection"
        echo ""
        
        read -p "Select operation: " choice
        
        case $choice in
            1)
                read -p "Enter IP address with CIDR (e.g., 192.168.1.10/24): " ip_cidr
                if [[ "$ip_cidr" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/[0-9]+$ ]]; then
                    COMMAND_PREVIEW="ip addr add $ip_cidr dev $SELECTED_INTERFACE"
                    execute_with_preview
                else
                    echo "Invalid IP/CIDR format."
                    read -p "Press Enter to continue..."
                fi
                ;;
            2)
                echo "Current IP addresses on $SELECTED_INTERFACE:"
                ip addr show dev "$SELECTED_INTERFACE" 2>/dev/null | grep -E "inet\s" | awk '{print "  "$2}' || echo "  No IP addresses found"
                echo ""
                read -p "Enter IP to delete (with CIDR): " ip_cidr
                if [ -n "$ip_cidr" ]; then
                    COMMAND_PREVIEW="ip addr del $ip_cidr dev $SELECTED_INTERFACE"
                    execute_with_preview
                fi
                ;;
            3)
                read -p "Are you sure you want to flush ALL IPs from $SELECTED_INTERFACE? (yes/no): " confirm_flush
                if [[ "$confirm_flush" == "yes" ]]; then
                    COMMAND_PREVIEW="ip addr flush dev $SELECTED_INTERFACE"
                    execute_with_preview
                fi
                ;;
            4)
                echo ""
                ip addr show dev "$SELECTED_INTERFACE" 2>/dev/null || echo "Interface not found"
                read -p "Press Enter to continue..."
                ;;
            0)
                return
                ;;
            *)
                echo "Invalid option."
                sleep 1
                ;;
        esac
    done
}

module_route() {
    while true; do
        clear
        echo "=== ROUTING MODULE ==="
        echo "1. Show routing table"
        echo "2. Add route"
        echo "3. Delete route"
        echo "4. Add default gateway"
        echo "5. Flush routing table"
        echo "0. Back to interface selection"
        echo ""
        
        read -p "Select operation: " choice
        
        case $choice in
            1)
                echo ""
                ip route show
                read -p "Press Enter to continue..."
                ;;
            2)
                read -p "Enter destination network (e.g., 10.0.0.0/24): " dest_net
                read -p "Enter gateway (or 'dev <interface>' for direct): " gateway
                COMMAND_PREVIEW="ip route add $dest_net via $gateway"
                execute_with_preview
                ;;
            3)
                read -p "Enter route to delete (e.g., 10.0.0.0/24): " route_to_delete
                COMMAND_PREVIEW="ip route del $route_to_delete"
                execute_with_preview
                ;;
            4)
                read -p "Enter default gateway IP: " default_gw
                COMMAND_PREVIEW="ip route add default via $default_gw"
                execute_with_preview
                ;;
            5)
                read -p "Are you sure you want to flush the routing table? (yes/no): " confirm_flush
                if [[ "$confirm_flush" == "yes" ]]; then
                    COMMAND_PREVIEW="ip route flush table main"
                    execute_with_preview
                fi
                ;;
            0)
                return
                ;;
            *)
                echo "Invalid option."
                sleep 1
                ;;
        esac
    done
}

# ==================== MAIN PROGRAM FLOW ====================
main() {
    initialize
    
    while true; do
        # Step 1: Select interface
        select_interface
        select_result=$?
        
        if [ $select_result -eq 2 ]; then
            continue  # Applied persistent configs, go back to interface selection
        elif [ $select_result -ne 0 ]; then
            continue  # Invalid selection, try again
        fi
        
        # Step 2: Select module for the chosen interface
        while true; do
            clear
            echo "========================================"
            echo "    Configuration for: $SELECTED_INTERFACE"
            echo "========================================"
            show_current_state
            echo "Select module to configure:"
            echo "1. LINK Configuration (Layer 2)"
            echo "2. ADDRESS Configuration (IP Addresses)"
            echo "3. ROUTE Configuration"
            echo "4. NEIGHBOR Configuration (ARP)"
            echo "5. RULE Configuration (Policy Routing)"
            echo "0. Back to interface selection"
            echo ""
            
            read -p "Select module: " module_choice
            
            case $module_choice in
                1) module_link ;;
                2) module_address ;;
                3) module_route ;;
                4) 
                    echo "Neighbor module not yet implemented"
                    read -p "Press Enter to continue..."
                    ;;
                5) 
                    echo "Rule module not yet implemented"
                    read -p "Press Enter to continue..."
                    ;;
                0)
                    break  # Go back to interface selection
                    ;;
                *)
                    echo "Invalid option."
                    sleep 1
                    ;;
            esac
        done
    done
}

# ==================== SCRIPT START ====================
# Trap for safe exit
trap 'echo -e "\nSaving configurations before exit..."; save_to_persistent "SYSTEM" "EXIT" "User interrupted"; exit 0' INT TERM

# Start the main program
main